// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeListDemo.Model;

namespace TreeListDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TreeListDemo.Model.Fields", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayFieldprefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("FieldType")
                        .HasColumnType("tinyint");

                    b.Property<string>("FieldsPrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkingFieldPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryTable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Fields", "dbo");
                });

            modelBuilder.Entity("TreeListDemo.Model.View", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("View", "dbo");
                });

            modelBuilder.Entity("TreeListDemo.Model.ViewField", b =>
                {
                    b.Property<int>("ViewID")
                        .HasColumnType("int");

                    b.Property<int>("FieldID")
                        .HasColumnType("int");

                    b.HasKey("ViewID", "FieldID");

                    b.HasIndex("FieldID");

                    b.ToTable("ViewField", "dbo");
                });

            modelBuilder.Entity("TreeListDemo.Model.ViewField", b =>
                {
                    b.HasOne("TreeListDemo.Model.Fields", "field")
                        .WithMany()
                        .HasForeignKey("FieldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreeListDemo.Model.View", "view")
                        .WithMany()
                        .HasForeignKey("ViewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("field");

                    b.Navigation("view");
                });
#pragma warning restore 612, 618
        }
    }
}
